server:
    port: 8081
spring:
    thymeleaf:
        cache: false
        enabled: false
    application:
        name: pandora
    datasource:
        url: jdbc:mysql://47.98.54.210:3306/toolink?autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: a123456
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 20
        max-active: 100
        max-idle: 5
        max-wait: 10000
        min-idle: 1
        testOnBorrow: true
        validationQuery: SELECT 1
#    redis:
#        database: 1
#        host: 192.168.1.134
#        port: 6379
#        password:
#        pool:
#            max-active: 8
#            max-wait: -1
#            max-idle: 8
#            min-idle: 0
#        timeout: 0

## 日志支持
logging:
    file: ./log/pandora.log
    level:
        com:
            xulu: WARN
mybatis:
    mapperLocations: classpath:mybatis/*.xml
    typeAliasesPackage: com.xulu.pandora